name = "beacon"
main = "src/index.ts"
compatibility_date = "2026-07-09"

[[routes]]
pattern = "rmm-api.cloud.synertekcs.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "beacon"
database_id = "4a25c09a-ecc7-4a06-9606-380e754cbd9d"
migrations_dir = "../migrations"

[triggers]
crons = ["*/2 * * * *"]

[[durable_objects.bindings]]
name = "SESSION"
class_name = "SessionRelay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionRelay"]
